apiVersion: v1
kind: Service
metadata:
  name: taskproject-svc
#  namespace: project
  labels:
    app: tsp
spec:
  type: NodePort
  selector:
    app: tsp
  ports:
  - port: 8080
    protocol: TCP
    name: frontend-port
#    name: dbtool-port
  - port: 8081
    targetPort: 80
    protocol: TCP
    name: backend-port
status:
  loadBalancer: {}