apiVersion: v1 # Includes the Service for lazyness
kind: Service
metadata:
  name: taskproject-svc
  namespace: project
  labels:
    app: tsp
spec:
  selector:
    app: tsp
  clusterIP: None
  ports:
  - port: 8080
    name: frontend-port
  - port: 8081
    name: backend-port
  - port: 3306
    name: mariadb-port
#  - port: 8080
#    name: dbtool-port
