apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/configmap_env.yaml
  - manifests/configmap_sql.yaml
  - manifests/cronjob.yaml
  - manifests/ingress.yaml
  - manifests/service.yaml
  - manifests/statefulset.yaml
images:
  - name: PROJECT/FRONTEND
    newName: gcr.io/PROJECT_ID/IMAGE/FRONTEND
  - name: PROJECT/BACKEND
    newName: gcr.io/PROJECT_ID/IMAGE/BACKEND
  - name: PROJECT/MARIADB
    newName: gcr.io/PROJECT_ID/IMAGE/MARIADB
  - name: PROJECT/CRONJOB
    newName: gcr.io/PROJECT_ID/IMAGE/CRONJOB
  - name: PROJECT/ADMINER
    newName: gcr.io/PROJECT_ID/IMAGE/ADMINER