services:
  frontend:
    image: server102
    build:
      context: .
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    environment:
      - PORT=8080
      - NGINX_PORT=80