apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/configmap_env.yaml
  - manifests/cronjob.yaml
  - manifests/ingress.yaml
  - manifests/service.yaml
  - manifests/deployment.yaml
  - manifests/service-account.yaml
  - manifests/backend-claim0-persistentvolumeclaim.yaml
images:
  - name: PROJECT/FRONTEND
    newName: dwk-gke-360910/FRONTEND
  - name: PROJECT/BACKEND
    newName: dwk-gke-360910/BACKEND
  - name: PROJECT/CRONJOB
    newName: dwk-gke-360910/CRONJOB
  - name: PROJECT/ADMINER
    newName: dwk-gke-360910/ADMINER