apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: taskproject-svc
spec:
  type: ClusterIP
  selector:
    app: taskproject # This is the app as declared in the Deployment
  ports:
    - name: frontend-port
      port: 2345 # This is a port that is available to the cluster
      protocol: TCP
      targetPort: 8080 # This is the target port
    - name: backend-port
      port: 2346 # This is a port that is available to the cluster
      protocol: TCP
      targetPort: 8081 # This is the target port
